# This is a basic workflow to help you get started with Actions

name: Build and Push to Docker Hub

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: test-environment

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/data-in-cloud:${{ env.DATE }} -t ${{ secrets.DOCKER_USERNAME }}/data-in-cloud .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/data-in-cloud --all-tags
